directories:
  output: dist_electron
  buildResources: build
appId: com.gemduel.app
productName: Gem Duel
files:
  - filter:
      - dist/**/*
      - electron/**/*
      - package.json
win:
  target:
    - nsis
  icon: public/vite.svg
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  createDesktopShortcut: true
electronVersion: 39.2.7
